/**
 * Registration-client-api
 * Interage com o registration server (eureka) para registar esta instância ou obter servidores com o qual pode comunicar
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator 2.4.17.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/*
 * EndpointsApi.h
 *
 * 
 */

#ifndef IO_SWAGGER_CLIENT_API_EndpointsApi_H_
#define IO_SWAGGER_CLIENT_API_EndpointsApi_H_


#include "../ApiClient.h"

#include "Endpoint.h"
#include <cpprest/details/basic_types.h>

#include <boost/optional.hpp>

namespace io {
namespace swagger {
namespace client {
namespace api {

using namespace io::swagger::client::model;

class  EndpointsApi
{
public:
    EndpointsApi( std::shared_ptr<ApiClient> apiClient );
    virtual ~EndpointsApi();
    /// <summary>
    /// Regista o endpoint no servidor eureka
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    pplx::task<void> _register(
    );
    /// <summary>
    /// Obtém o melhor endpoint para o serviço {service}
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="service">Service name</param>
    pplx::task<std::shared_ptr<Endpoint>> getServiceEndpoint(
        utility::string_t service
    );
    /// <summary>
    /// Obtém todos os endpoints registados em nome do serviço {service}
    /// </summary>
    /// <remarks>
    /// 
    /// </remarks>
    /// <param name="service">Service name</param>
    pplx::task<std::vector<std::shared_ptr<Endpoint>>> getServiceEndpoints(
        utility::string_t service
    );

protected:
    std::shared_ptr<ApiClient> m_ApiClient;
};

}
}
}
}

#endif /* IO_SWAGGER_CLIENT_API_EndpointsApi_H_ */

