template header

rule
ruleId
eventType
decision
priority

package pt.unl.fct.miei.usmanagement.manager.master.management.management.rulesystem;

import pt.unl.fct.miei.usmanagement.manager.management.rulesystem.decision.Decision;

global pt.unl.fct.miei.usmanagement.manager.management.rulesystem.decision.Decision containerDecision;

template "container"

rule "rule_container_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    containerDecision.setDecision(@{decision});
    containerDecision.setPriority(@{priority});
end

end template