/*
 * Register-go API
 * Get apps endpoints from eureka
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import java.util.List;

import io.swagger.client.ApiException;
import io.swagger.client.model.App;
import io.swagger.client.model.Msg;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for AppsApi
 */
@Ignore
public class AppsApiTest {

  private final AppsApi api = new AppsApi();


  /**
   * Get all apps endpoints by app name
   * <p>
   * Returns an array of app endpoint
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getAllAppsByNameTest() throws ApiException {
    String appName = null;
    List<App> response = api.getAllAppsByName(appName);

    // TODO: test validations
  }

  /**
   * Get an app endpoint by app name
   * <p>
   * Returns an app endpoint
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void getAppsByNameTest() throws ApiException {
    String appName = null;
    App response = api.getAppsByName(appName);

    // TODO: test validations
  }

  /**
   * Register an app on Eureka
   * <p>
   * Returns success
   *
   * @throws ApiException if the Api call fails
   */
  @Test
  public void registerTest() throws ApiException {
    Msg response = api.register();

    // TODO: test validations
  }

}
