template header

rule
ruleId
eventType
decision
priority

package pt.unl.fct.miei.usmanagement.manager.worker.management.rulesystem;

import pt.unl.fct.miei.usmanagement.manager.database.rulesystem.rules.RuleDecision.*;

global RuleDecision hostDecision;

template "host"

rule "rule_host_@{ruleId}" salience @{priority}
when
    @{eventType}(@{rule})
then
    hostDecision.setDecision(@{decision});
    hostDecision.setPriority(@{priority});
end

end template